<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>Nalazoo</title>
        <link rel="shortcut icon" href="img/common/pavi.png">
        <!--ios용 아이콘-->
        <link rel="apple-touch-icon-precomposed" href="img/common/ios_pavi.ico"> 
        <!--안드로이드용 아이콘-->
        <link rel="icon" type="images/png" href="img/common/and_pavi.png">
        <link rel="stylesheet" href="css/common.css">
        <link rel="stylesheet" href="css/layout.css">
        <link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="css/sub.css">
        
        <script src="js/jquery-1.12.0.min.js"></script>
        <script src="js/jquery.flexslider-min.js"></script>
        <script src="js/common.js"></script>
        <script src="js/sub.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js" integrity="sha512-VEBjfxWUOyzl0bAwh4gdLEaQyDYPvLrZql3pw1ifgb6fhEvZl9iDDehwHZ+dsMzA0Jfww8Xt7COSZuJ/slxc4Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    </head>

</html>